package no.nav.folketrygdloven.beregningsgrunnlag.regelmodell;

public enum PeriodeÅrsak {
    UDEFINERT,
    NATURALYTELSE_BORTFALT,
    ARBEIDSFORHOLD_AVSLUTTET,
    NATURALYTELSE_TILKOMMER,
    ENDRING_I_REFUSJONSKRAV,
    REFUSJON_OPPHØRER,
    GRADERING,
    GRADERING_OPPHØRER,
    ENDRING_I_AKTIVITETER_SØKT_FOR
}
